name: 'Hangar Publish'
description: 'Upload Minecraft plugins to Hangar (PaperMC) with comprehensive file and dependency management'

branding:
  icon: 'upload'
  color: 'gray-dark'

inputs:
  api_token:
    description: 'Hangar API token for authentication (generate from your Hangar profile settings)'
    required: true

  slug:
    description: 'Project slug/identifier on Hangar (e.g., "my-awesome-plugin")'
    required: true

  version:
    description: 'Plugin version string (e.g., "1.0.0", "2.1.3-SNAPSHOT")'
    required: true

  channel:
    description: 'Release channel type (e.g., "Release", "Beta", "Alpha", "Snapshot")'
    required: true

  description:
    description: 'Markdown-formatted release description/changelog'
    required: false
    default: ''

  files:
    description: |
      JSON array of files to upload. Each file entry must specify:
      - `path` (glob pattern for local files) OR `url` & `externalUrl` for external files
      - `platforms`: Array of `["PAPER", "VELOCITY", "WATERFALL"]`

      Example:
      [
        {
          "path": "build/libs/*.jar",
          "platforms": ["PAPER"]
        },
        {
          "path": "**/build/libs/!(*-sources|*-javadoc).jar",
          "platforms": ["VELOCITY"]
        },
        {
          "url": true,
          "externalUrl": "https://example.com/plugin.jar",
          "platforms": ["PAPER", "VELOCITY"]
        }
      ]
    required: true

  plugin_dependencies:
    description: |
      JSON object defining project dependecies per platform.
      
      Each platform maps to an array of dependency objects with:
      - name: Project slug or name (if using externalUrl)
      - required: Boolean indicating if the dependency is required
      - externalUrl (optional): URL to an external project if not on Hangar

      Example:
      {
        "PAPER": [
          {
            "name": "Vault",
            "required": true
          },
          {
            "name": "WorldEdit",
            "required": false
          },
          {
            "name": "PlaceholderAPI", 
            "required": false,
            "externalUrl": "https://www.spigotmc.org/resources/placeholderapi.6245/"
          }
        ]
      }
    required: false
    default: ''

  platform_dependencies:
    description: |
      JSON object mapping platform names to version patterns. Supports semver-like patterns for PAPER platform only.
      PAPER versions are resolved from Mojang's official API.
      
      Supported patterns for PAPER:
      - Exact: ["1.20.1", "1.19.4"]  
      - Range: [">=1.19.0"]
      - Patch: ["~1.20.0"] (1.20.x versions)
      - Compatible: ["^1.19.0"] (1.19+ versions)
      - Wildcard: ["1.20.x"]
      
      VELOCITY/WATERFALL use exact versions only:
      Example: {"PAPER": [">=1.19.0"], "VELOCITY": ["3.2.0"], "WATERFALL": ["1.19"]}
    required: false
    default: ''

outputs:
  upload_url:
    description: 'Direct URL to the uploaded version page on Hangar'

runs:
  using: 'node24'
  main: 'dist/index.js'